# For details on connection pooling, see Rails configuration guide
# https://guides.rubyonrails.org/configuring.html#database-pooling

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: queue_demo_development
  solid_queue:
    <<: *default
    database: queue_demo_solid_queue_development
    migrations_paths: db/solid_queue_migrate

test:
  primary:
    <<: *default
    database: queue_demo_test
  solid_queue:
    <<: *default
    database: queue_demo_solid_queue_test
    migrations_paths: db/solid_queue_migrate

production:
  <<: *default
  primary:
    <<: *default
  solid_queue:
    <<: *default
    url: <%= ENV["SOLID_QUEUE_DATABASE_URL"] %>
    migrations_paths: db/solid_queue_migrate
